name: salesops
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.3
  - numpy=2.3.4
  - scikit-learn=1.7.2
  - matplotlib
  - seaborn
  - scipy
  - ipykernel
  - notebook
  - pip
  - pyarrow
  - pip:
      - google-adk
      - plotly==6.0.0
      - python-dotenv==1.0.0
      - tqdm==4.66.1
      - requests==2.31.0
      - pytest==7.4.2
      - fastapi==0.121.2
      - uvicorn==0.38.0
